---
version: "3.8"
services:
  movies:
    image: saikrishnass/paymovies:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: saikrishnass/paytrain:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  recharge:
    image: saikrishnass/payrecharge:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  dth:
    image: saikrishnass/paymdth:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
